In [6]:
from statsbombpy import sb
import pandas as pd
from keystone_scouting.utilities.bq_utils import BigQueryConnector

GCP_PROJECT = "lgc-data"
GCP_DATASET = "keystone_scouting"
pipeline = BigQueryConnector(GCP_PROJECT)

%load_ext autoreload
%autoreload 2

/Users/lgc/Documents/keystone_scouting/venv/lib/python3.11/site-packages/google/auth/_default.py:113: UserWarning: Your application has authenticated using end user credentials from Google Cloud SDK without a quota project. You might receive a "quota exceeded" or "API not enabled" error. See the following page for troubleshooting: https://cloud.google.com/docs/authentication/adc-troubleshooting/user-creds.
  warnings.warn(_CLOUD_SDK_CREDENTIALS_WARNING)

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [7]:
# get competitions and display all men's champions league rows
comps = sb.competitions()
display(comps[comps['competition_id'] == 16])

/Users/lgc/Documents/keystone_scouting/venv/lib/python3.11/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

,competition_id,season_id,country_name,competition_name,competition_gender,competition_youth,competition_international,season_name,match_updated,match_updated_360,match_available_360,match_available
3,16,4,Europe,Champions League,male,False,False,2018/2019,2026-05-15T15:54:04.598614,2021-06-13T16:17:31.694,None,2026-05-15T15:54:04.598614
4,16,1,Europe,Champions League,male,False,False,2017/2018,2024-02-13T02:35:28.134882,2021-06-13T16:17:31.694,None,2024-02-13T02:35:28.134882
5,16,2,Europe,Champions League,male,False,False,2016/2017,2024-02-13T02:37:32.205154,2021-06-13T16:17:31.694,None,2024-02-13T02:37:32.205154
6,16,27,Europe,Champions League,male,False,False,2015/2016,2024-06-12T07:45:38.786894,2021-06-13T16:17:31.694,None,2024-06-12T07:45:38.786894
7,16,26,Europe,Champions League,male,False,False,2014/2015,2024-02-12T12:49:54.914228,2021-06-13T16:17:31.694,None,2024-02-12T12:49:54.914228
8,16,25,Europe,Champions League,male,False,False,2013/2014,2024-02-12T12:48:48.479157,2021-06-13T16:17:31.694,None,2024-02-12T12:48:48.479157
9,16,24,Europe,Champions League,male,False,False,2012/2013,2024-02-12T12:47:34.340413,2021-06-13T16:17:31.694,None,2024-02-12T12:47:34.340413
10,16,23,Europe,Champions League,male,False,False,2011/2012,2024-02-13T02:36:35.698340,2021-06-13T16:17:31.694,None,2024-02-13T02:36:35.698340
11,16,22,Europe,Champions League,male,False,False,2010/2011,2024-02-12T12:53:03.944320,2021-06-13T16:17:31.694,None,2024-02-12T12:53:03.944320
12,16,21,Europe,Champions League,male,False,False,2009/2010,2024-02-12T12:49:25.017694,2021-06-13T16:17:31.694,None,2024-02-12T12:49:25.017694
13,16,41,Europe,Champions League,male,False,False,2008/2009,2024-02-13T07:02:54.657056,2021-06-13T16:17:31.694,None,2024-02-13T07:02:54.657056
14,16,39,Europe,Champions League,male,False,False,2006/2007,2024-02-12T13:48:23.967222,2021-06-13T16:17:31.694,None,2024-02-12T13:48:23.967222
15,16,37,Europe,Champions League,male,False,False,2004/2005,2025-06-24T09:44:09.039471,2021-06-13T16:17:31.694,None,2025-06-24T09:44:09.039471
16,16,44,Europe,Champions League,male,False,False,2003/2004,2025-06-24T13:57:37.321382,2021-06-13T16:17:31.694,None,2025-06-24T13:57:37.321382
17,16,76,Europe,Champions League,male,False,False,1999/2000,2025-06-23T12:34:36.649637,2021-06-13T16:17:31.694,None,2025-06-23T12:34:36.649637
18,16,277,Europe,Champions League,male,False,False,1972/1973,2024-02-13T14:25:16.532771,None,None,2024-02-13T14:25:16.532771
19,16,71,Europe,Champions League,male,False,False,1971/1972,2024-02-12T14:25:01.735880,2021-06-13T16:17:31.694,None,2024-02-12T14:25:01.735880
20,16,276,Europe,Champions League,male,False,False,1970/1971,2024-02-13T14:24:12.213582,None,None,2024-02-13T14:24:12.213582

In [8]:
# Get all matches from all seasons of men's champions league (competition_id = 16)
ucl_seasons = comps[comps['competition_id'] == 16]['season_id'].tolist()
ucl_matches = pd.concat([sb.matches(competition_id=16, season_id=season_id) for season_id in ucl_seasons], ignore_index=True)
display(ucl_matches)

/Users/lgc/Documents/keystone_scouting/venv/lib/python3.11/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/Users/lgc/Documents/keystone_scouting/venv/lib/python3.11/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/Users/lgc/Documents/keystone_scouting/venv/lib/python3.11/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/Users/lgc/Documents/keystone_scouting/venv/lib/python3.11/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/Users/lgc/Documents/keystone_scouting/venv/lib/python3.11/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/Users/lgc/Documents/keystone_scouting/venv/lib/python3.11/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/Users/lgc/Documents/keystone_scouting/venv/lib/python3.11/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/Users/lgc/Documents/keystone_scouting/venv/lib/python3.11/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/Users/lgc/Documents/keystone_scouting/venv/lib/python3.11/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/Users/lgc/Documents/keystone_scouting/venv/lib/python3.11/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/Users/lgc/Documents/keystone_scouting/venv/lib/python3.11/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/Users/lgc/Documents/keystone_scouting/venv/lib/python3.11/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/Users/lgc/Documents/keystone_scouting/venv/lib/python3.11/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/Users/lgc/Documents/keystone_scouting/venv/lib/python3.11/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/Users/lgc/Documents/keystone_scouting/venv/lib/python3.11/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/Users/lgc/Documents/keystone_scouting/venv/lib/python3.11/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/Users/lgc/Documents/keystone_scouting/venv/lib/python3.11/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/Users/lgc/Documents/keystone_scouting/venv/lib/python3.11/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

,match_id,match_date,kick_off,home_score,away_score,match_status,match_status_360,last_updated,last_updated_360,match_week,...,home_manager_country_name,away_manager_id,away_manager_name,away_manager_nickname,away_manager_dob,away_manager_country_id,away_manager_country_name,data_version,shot_fidelity_version,xy_fidelity_version
0,22912,2019-06-01,21:00:00.000,0,2,available,scheduled,2024-02-12T12:58:06.654567,2021-06-13T16:17:31.694,13,...,Argentina,94.0,Jürgen Klopp,None,1967-06-16,85.0,Germany,1.1.0,2,2
1,18245,2018-05-26,20:45:00.000,3,1,available,scheduled,2024-02-13T02:35:28.134882,2021-06-13T16:17:31.694,7,...,France,94.0,Jürgen Klopp,None,1967-06-16,85.0,Germany,1.1.0,2,2
2,18244,2017-06-03,20:45:00.000,1,4,available,scheduled,2024-02-13T02:37:32.205154,2021-06-13T16:17:31.694,7,...,Italy,56.0,Zinédine Zidane,None,1972-06-23,78.0,France,1.0.3,None,None
3,18243,2016-05-28,20:45:00.000,1,1,available,scheduled,2024-06-12T07:45:38.786894,2021-06-13T16:17:31.694,1,...,France,230.0,Diego Pablo Simeone,Diego Simeone,1970-04-28,11.0,Argentina,1.0.3,None,None
4,18242,2015-06-06,20:45:00.000,1,3,available,scheduled,2024-02-12T12:49:54.914228,2021-06-13T16:17:31.694,1,...,Italy,793.0,Luis Enrique Martínez García,Luis Enrique,1970-05-08,214.0,Spain,1.0.3,None,None
5,18241,2014-05-24,20:45:00.000,4,1,available,scheduled,2024-02-12T12:48:48.479157,2021-06-13T16:17:31.694,1,...,Italy,230.0,Diego Pablo Simeone,Diego Simeone,1970-04-28,11.0,Argentina,1.0.3,None,None
6,18240,2013-05-25,20:45:00.000,1,2,available,scheduled,2024-02-12T12:47:34.340413,2021-06-13T16:17:31.694,1,...,Germany,444.0,Josef Heynckes,None,1945-05-09,85.0,Germany,1.0.3,None,None
7,18237,2012-05-19,20:45:00.000,1,1,available,scheduled,2024-02-13T02:36:35.698340,2021-06-13T16:17:31.694,1,...,Germany,789.0,Roberto Di Matteo,None,1970-05-29,112.0,Italy,1.0.3,None,None
8,18236,2011-05-28,20:45:00.000,3,1,available,scheduled,2024-02-12T12:53:03.944320,2021-06-13T16:17:31.694,1,...,Spain,790.0,Alex Ferguson,None,1941-12-31,201.0,Scotland,1.0.3,None,None
9,18235,2010-05-22,20:45:00.000,0,2,available,scheduled,2024-02-12T12:49:25.017694,2021-06-13T16:17:31.694,1,...,Netherlands,383.0,José Mario Felix dos Santos Mourinho,José Mourinho,1963-01-26,183.0,Portugal,1.0.3,None,None
10,3750201,2009-05-27,20:45:00.000,2,0,available,scheduled,2024-02-13T07:02:54.657056,2021-06-13T16:17:31.694,1,...,Spain,790.0,Alex Ferguson,None,1941-12-31,201.0,Scotland,1.1.0,2,2
11,3750200,2007-05-23,20:45:00.000,2,1,available,scheduled,2024-02-12T13:48:23.967222,2021-06-13T16:17:31.694,1,...,Italy,148.0,Rafael Benítez Maudes,Rafael Benítez,1960-04-16,214.0,Spain,1.1.0,2,2
12,2302764,2005-05-25,None,3,3,available,scheduled,2025-06-24T09:44:09.039471,2021-06-13T16:17:31.694,1,...,Italy,148.0,Rafael Benítez Maudes,Rafael Benítez,1960-04-16,214.0,Spain,1.1.0,2,2
13,3752619,2004-05-26,None,0,3,available,scheduled,2025-06-24T13:57:37.321382,2021-06-13T16:17:31.694,1,...,France,383.0,José Mario Felix dos Santos Mourinho,José Mourinho,1963-01-26,183.0,Portugal,1.1.0,2,2
14,3750240,1999-11-23,None,2,0,available,scheduled,2025-06-23T12:34:36.649637,2021-06-13T16:17:31.694,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.1.0,2,2
15,3888706,1973-05-30,22:30:00.000,1,0,available,unscheduled,2024-02-13T14:25:16.532771,None,1,...,Romania,1003281.0,Cestmir Vycpalek,None,1921-05-15,60.0,Czech Republic,1.1.0,2,2
16,3750235,1972-05-31,None,2,0,available,scheduled,2024-02-12T14:25:01.735880,2021-06-13T16:17:31.694,13,...,Romania,1001761.0,Giovanni Invernizzi,None,1931-08-26,112.0,Italy,1.1.0,2,2
17,3888711,1971-06-02,22:45:00.000,2,0,available,unscheduled,2024-02-13T14:24:12.213582,None,1,...,Netherlands,1003271.0,Ferenc Puskás,None,1927-04-01,103.0,Hungary,1.1.0,2,2

In [9]:
pipeline.upload_dataframe(ucl_matches, GCP_DATASET, "sb_matches")

🚀 Streaming via your personal account to lgc-data.keystone_scouting.sb_matches...

/Users/lgc/Documents/keystone_scouting/venv/lib/python3.11/site-packages/google/cloud/bigquery/_pandas_helpers.py:486: FutureWarning: Loading pandas DataFrame into BigQuery will require pandas-gbq package version 0.26.1 or greater in the future. Tried to import pandas-gbq and got: No module named 'pandas_gbq'
  warnings.warn(

📬 Job tracking ID: 58dfd841-4714-4a86-b7c9-fef21ab6611f. Processing in background...

In [18]:
import time
import json
print("🚀 Commencing JSON-variant micro-batch stream...")

for i, match in enumerate(ucl_matches.iterrows(), 1):
    match_id = match[1]['match_id']
    print(f"📦 [{i}/{len(ucl_matches)}] Streaming Match ID: {match_id} to JSON block...")
    
    # 1. Fetch raw events (keep columns exactly as they come)
    events_df = sb.events(match_id=match_id)
    
    # 2. Build a clean, structured JSON payload for every single row
    json_records = events_df.to_dict(orient="records")
    
    # 3. Build a compact, predictable 3-column DataFrame
    staging_df = pd.DataFrame({
        "match_id": int(match_id),
        "event_id": events_df['id'],
        "index": events_df.index,  # Keep original event ID for traceability
        "ingested_at": pd.Timestamp.now(tz="UTC"),
        # Stringify each row dictionary into a raw JSON string
        "event_payload": [
            json.dumps({k: v for k, v in record.items() if k not in ['id', 'index', 'match_id']})
            for record in json_records
        ]
    })
    
    # 4. Stream to BigQuery. 
    # Use append=False on the VERY FIRST iteration to clear old run tracking, then True.
    is_append = False if i == 1 else True
    pipeline.upload_dataframe(staging_df, GCP_DATASET, "sb_events_raw", append=is_append)
    
    time.sleep(0.2)

print("✅ Success! Raw telemetry securely isolated inside BigQuery.")

print("🚀 All events streamed successfully with zero missing columns!")

🚀 Commencing JSON-variant micro-batch stream...
📦 [1/18] Streaming Match ID: 22912 to JSON block...

/Users/lgc/Documents/keystone_scouting/venv/lib/python3.11/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

🚀 Streaming via your personal account to lgc-data.keystone_scouting.sb_events_raw...

/Users/lgc/Documents/keystone_scouting/venv/lib/python3.11/site-packages/google/cloud/bigquery/_pandas_helpers.py:486: FutureWarning: Loading pandas DataFrame into BigQuery will require pandas-gbq package version 0.26.1 or greater in the future. Tried to import pandas-gbq and got: No module named 'pandas_gbq'
  warnings.warn(

📬 Job tracking ID: d026bfae-6117-4f40-b59e-6adfec00f6c4. Processing in background...
📦 [2/18] Streaming Match ID: 18245 to JSON block...

/Users/lgc/Documents/keystone_scouting/venv/lib/python3.11/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

🚀 Streaming via your personal account to lgc-data.keystone_scouting.sb_events_raw...

/Users/lgc/Documents/keystone_scouting/venv/lib/python3.11/site-packages/google/cloud/bigquery/_pandas_helpers.py:486: FutureWarning: Loading pandas DataFrame into BigQuery will require pandas-gbq package version 0.26.1 or greater in the future. Tried to import pandas-gbq and got: No module named 'pandas_gbq'
  warnings.warn(

📬 Job tracking ID: a3b82455-9b88-4a83-94b5-4ec8a9bbb329. Processing in background...
📦 [3/18] Streaming Match ID: 18244 to JSON block...

/Users/lgc/Documents/keystone_scouting/venv/lib/python3.11/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

🚀 Streaming via your personal account to lgc-data.keystone_scouting.sb_events_raw...

/Users/lgc/Documents/keystone_scouting/venv/lib/python3.11/site-packages/google/cloud/bigquery/_pandas_helpers.py:486: FutureWarning: Loading pandas DataFrame into BigQuery will require pandas-gbq package version 0.26.1 or greater in the future. Tried to import pandas-gbq and got: No module named 'pandas_gbq'
  warnings.warn(

📬 Job tracking ID: 046bf29c-3454-44e4-9a06-008b3c512cc8. Processing in background...
📦 [4/18] Streaming Match ID: 18243 to JSON block...

/Users/lgc/Documents/keystone_scouting/venv/lib/python3.11/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

🚀 Streaming via your personal account to lgc-data.keystone_scouting.sb_events_raw...

/Users/lgc/Documents/keystone_scouting/venv/lib/python3.11/site-packages/google/cloud/bigquery/_pandas_helpers.py:486: FutureWarning: Loading pandas DataFrame into BigQuery will require pandas-gbq package version 0.26.1 or greater in the future. Tried to import pandas-gbq and got: No module named 'pandas_gbq'
  warnings.warn(

📬 Job tracking ID: c9b7e0a0-0bf7-4a79-afbd-04de5717e1ac. Processing in background...
📦 [5/18] Streaming Match ID: 18242 to JSON block...

/Users/lgc/Documents/keystone_scouting/venv/lib/python3.11/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

🚀 Streaming via your personal account to lgc-data.keystone_scouting.sb_events_raw...

/Users/lgc/Documents/keystone_scouting/venv/lib/python3.11/site-packages/google/cloud/bigquery/_pandas_helpers.py:486: FutureWarning: Loading pandas DataFrame into BigQuery will require pandas-gbq package version 0.26.1 or greater in the future. Tried to import pandas-gbq and got: No module named 'pandas_gbq'
  warnings.warn(

📬 Job tracking ID: ee667b79-b45a-4114-b004-b2b77b9bf92c. Processing in background...
📦 [6/18] Streaming Match ID: 18241 to JSON block...

/Users/lgc/Documents/keystone_scouting/venv/lib/python3.11/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

🚀 Streaming via your personal account to lgc-data.keystone_scouting.sb_events_raw...

/Users/lgc/Documents/keystone_scouting/venv/lib/python3.11/site-packages/google/cloud/bigquery/_pandas_helpers.py:486: FutureWarning: Loading pandas DataFrame into BigQuery will require pandas-gbq package version 0.26.1 or greater in the future. Tried to import pandas-gbq and got: No module named 'pandas_gbq'
  warnings.warn(

📬 Job tracking ID: 923ae9ba-fd50-4255-b31b-90f68a87a156. Processing in background...
📦 [7/18] Streaming Match ID: 18240 to JSON block...

/Users/lgc/Documents/keystone_scouting/venv/lib/python3.11/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

🚀 Streaming via your personal account to lgc-data.keystone_scouting.sb_events_raw...

/Users/lgc/Documents/keystone_scouting/venv/lib/python3.11/site-packages/google/cloud/bigquery/_pandas_helpers.py:486: FutureWarning: Loading pandas DataFrame into BigQuery will require pandas-gbq package version 0.26.1 or greater in the future. Tried to import pandas-gbq and got: No module named 'pandas_gbq'
  warnings.warn(

📬 Job tracking ID: 567093b5-b6a3-472c-907c-260d0b5e666a. Processing in background...
📦 [8/18] Streaming Match ID: 18237 to JSON block...

/Users/lgc/Documents/keystone_scouting/venv/lib/python3.11/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

🚀 Streaming via your personal account to lgc-data.keystone_scouting.sb_events_raw...

/Users/lgc/Documents/keystone_scouting/venv/lib/python3.11/site-packages/google/cloud/bigquery/_pandas_helpers.py:486: FutureWarning: Loading pandas DataFrame into BigQuery will require pandas-gbq package version 0.26.1 or greater in the future. Tried to import pandas-gbq and got: No module named 'pandas_gbq'
  warnings.warn(

📬 Job tracking ID: c722f4af-3860-4781-bf52-6c917d723926. Processing in background...
📦 [9/18] Streaming Match ID: 18236 to JSON block...

/Users/lgc/Documents/keystone_scouting/venv/lib/python3.11/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

🚀 Streaming via your personal account to lgc-data.keystone_scouting.sb_events_raw...

/Users/lgc/Documents/keystone_scouting/venv/lib/python3.11/site-packages/google/cloud/bigquery/_pandas_helpers.py:486: FutureWarning: Loading pandas DataFrame into BigQuery will require pandas-gbq package version 0.26.1 or greater in the future. Tried to import pandas-gbq and got: No module named 'pandas_gbq'
  warnings.warn(

📬 Job tracking ID: 52dff0d6-886b-4a56-9f83-e346de12070b. Processing in background...
📦 [10/18] Streaming Match ID: 18235 to JSON block...

/Users/lgc/Documents/keystone_scouting/venv/lib/python3.11/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

🚀 Streaming via your personal account to lgc-data.keystone_scouting.sb_events_raw...

/Users/lgc/Documents/keystone_scouting/venv/lib/python3.11/site-packages/google/cloud/bigquery/_pandas_helpers.py:486: FutureWarning: Loading pandas DataFrame into BigQuery will require pandas-gbq package version 0.26.1 or greater in the future. Tried to import pandas-gbq and got: No module named 'pandas_gbq'
  warnings.warn(

📬 Job tracking ID: 1542fa14-6580-46b1-aee8-2a657891e75e. Processing in background...
📦 [11/18] Streaming Match ID: 3750201 to JSON block...

/Users/lgc/Documents/keystone_scouting/venv/lib/python3.11/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

🚀 Streaming via your personal account to lgc-data.keystone_scouting.sb_events_raw...

/Users/lgc/Documents/keystone_scouting/venv/lib/python3.11/site-packages/google/cloud/bigquery/_pandas_helpers.py:486: FutureWarning: Loading pandas DataFrame into BigQuery will require pandas-gbq package version 0.26.1 or greater in the future. Tried to import pandas-gbq and got: No module named 'pandas_gbq'
  warnings.warn(

📬 Job tracking ID: 81bd07db-c32f-4dce-8d80-cdf7ce4b637c. Processing in background...
📦 [12/18] Streaming Match ID: 3750200 to JSON block...

/Users/lgc/Documents/keystone_scouting/venv/lib/python3.11/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

🚀 Streaming via your personal account to lgc-data.keystone_scouting.sb_events_raw...

/Users/lgc/Documents/keystone_scouting/venv/lib/python3.11/site-packages/google/cloud/bigquery/_pandas_helpers.py:486: FutureWarning: Loading pandas DataFrame into BigQuery will require pandas-gbq package version 0.26.1 or greater in the future. Tried to import pandas-gbq and got: No module named 'pandas_gbq'
  warnings.warn(

📬 Job tracking ID: 33dbd8f6-7f64-4c12-badc-e03d22947bef. Processing in background...
📦 [13/18] Streaming Match ID: 2302764 to JSON block...

/Users/lgc/Documents/keystone_scouting/venv/lib/python3.11/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

🚀 Streaming via your personal account to lgc-data.keystone_scouting.sb_events_raw...

/Users/lgc/Documents/keystone_scouting/venv/lib/python3.11/site-packages/google/cloud/bigquery/_pandas_helpers.py:486: FutureWarning: Loading pandas DataFrame into BigQuery will require pandas-gbq package version 0.26.1 or greater in the future. Tried to import pandas-gbq and got: No module named 'pandas_gbq'
  warnings.warn(

📬 Job tracking ID: 0d05fbec-493e-46ec-b0c3-a6baddb89740. Processing in background...
📦 [14/18] Streaming Match ID: 3752619 to JSON block...

/Users/lgc/Documents/keystone_scouting/venv/lib/python3.11/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

🚀 Streaming via your personal account to lgc-data.keystone_scouting.sb_events_raw...

/Users/lgc/Documents/keystone_scouting/venv/lib/python3.11/site-packages/google/cloud/bigquery/_pandas_helpers.py:486: FutureWarning: Loading pandas DataFrame into BigQuery will require pandas-gbq package version 0.26.1 or greater in the future. Tried to import pandas-gbq and got: No module named 'pandas_gbq'
  warnings.warn(

📬 Job tracking ID: 809902e8-33ce-4e21-824c-e6583b44658d. Processing in background...
📦 [15/18] Streaming Match ID: 3750240 to JSON block...

/Users/lgc/Documents/keystone_scouting/venv/lib/python3.11/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

🚀 Streaming via your personal account to lgc-data.keystone_scouting.sb_events_raw...

/Users/lgc/Documents/keystone_scouting/venv/lib/python3.11/site-packages/google/cloud/bigquery/_pandas_helpers.py:486: FutureWarning: Loading pandas DataFrame into BigQuery will require pandas-gbq package version 0.26.1 or greater in the future. Tried to import pandas-gbq and got: No module named 'pandas_gbq'
  warnings.warn(

📬 Job tracking ID: 58cfaa30-eead-4a20-b217-d84f1364fd67. Processing in background...
📦 [16/18] Streaming Match ID: 3888706 to JSON block...

/Users/lgc/Documents/keystone_scouting/venv/lib/python3.11/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

🚀 Streaming via your personal account to lgc-data.keystone_scouting.sb_events_raw...

/Users/lgc/Documents/keystone_scouting/venv/lib/python3.11/site-packages/google/cloud/bigquery/_pandas_helpers.py:486: FutureWarning: Loading pandas DataFrame into BigQuery will require pandas-gbq package version 0.26.1 or greater in the future. Tried to import pandas-gbq and got: No module named 'pandas_gbq'
  warnings.warn(

📬 Job tracking ID: 932a74ca-f833-438d-a336-ddabb44e8992. Processing in background...
📦 [17/18] Streaming Match ID: 3750235 to JSON block...

/Users/lgc/Documents/keystone_scouting/venv/lib/python3.11/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

🚀 Streaming via your personal account to lgc-data.keystone_scouting.sb_events_raw...

/Users/lgc/Documents/keystone_scouting/venv/lib/python3.11/site-packages/google/cloud/bigquery/_pandas_helpers.py:486: FutureWarning: Loading pandas DataFrame into BigQuery will require pandas-gbq package version 0.26.1 or greater in the future. Tried to import pandas-gbq and got: No module named 'pandas_gbq'
  warnings.warn(

📬 Job tracking ID: b5b4052f-cc39-4ce0-a568-99d3de335a07. Processing in background...
📦 [18/18] Streaming Match ID: 3888711 to JSON block...

/Users/lgc/Documents/keystone_scouting/venv/lib/python3.11/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

🚀 Streaming via your personal account to lgc-data.keystone_scouting.sb_events_raw...

/Users/lgc/Documents/keystone_scouting/venv/lib/python3.11/site-packages/google/cloud/bigquery/_pandas_helpers.py:486: FutureWarning: Loading pandas DataFrame into BigQuery will require pandas-gbq package version 0.26.1 or greater in the future. Tried to import pandas-gbq and got: No module named 'pandas_gbq'
  warnings.warn(

📬 Job tracking ID: 683d8462-575d-4f66-b2a2-a2e3446b03e9. Processing in background...
✅ Success! Raw telemetry securely isolated inside BigQuery.
🚀 All events streamed successfully with zero missing columns!